"""
state.py
--------
Defines the shared global state that flows through the LangGraph StateGraph.
Every agent reads from and writes to this state object.
"""

from __future__ import annotations
from typing import TypedDict, Optional


class AgentLog(TypedDict):
    """A single LLMOps trace entry produced by one agent step."""
    timestamp: str
    agent: str
    tool_called: Optional[str]
    input_summary: str
    output_summary: str
    model: str
    duration_ms: float


class SharedState(TypedDict):
    """
    Global state passed between all agents in the pipeline.

    Fields
    ------
    input_path : str
        Absolute path to the local folder containing source code to review.
    code_files : dict[str, str]
        Mapping of {relative_filename: file_content} populated by the
        Coordinator after the file_reader_tool runs.
    analysis_results : dict
        Code-quality findings produced by the Code Analysis Agent.
        Shape: {filename: {"score": int, "issues": list[str], "summary": str}}
    security_results : dict
        Security findings produced by the Security Agent.
        Shape: {filename: {"severity": str, "findings": list[dict], "summary": str}}
    report_path : str
        Absolute path to the Markdown report generated by the Report Agent.
    agent_logs : list[AgentLog]
        Ordered list of LLMOps trace entries for observability.
    status : str
        Pipeline lifecycle status: "pending" | "reading" | "analyzing" |
        "auditing" | "reporting" | "done" | "error"
    error : str
        Human-readable error message; empty string when no error.
    """
    input_path: str
    code_files: dict
    analysis_results: dict
    security_results: dict
    report_path: str
    agent_logs: list
    status: str
    error: str


def initial_state(input_path: str) -> SharedState:
    """Return a fresh SharedState for a new pipeline run."""
    return SharedState(
        input_path=input_path,
        code_files={},
        analysis_results={},
        security_results={},
        report_path="",
        agent_logs=[],
        status="pending",
        error="",
    )
